version: '2'
services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 15672:15672      
      - 5672:5672
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  config:
    build: config
    ports:
      - 8888:8888
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    image: interac-config
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  registry:
    build: registry
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    image: interac-registry
    restart: always
    ports:
      - 8761:8761
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  gateway:
    build: gateway
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    image: interac-gateway
    restart: always
    ports:
      - 80:4000
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  auth-service:
    build: auth-service
    ports:
      - 5000:5000
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD      
      INTERAC_SERVICE_PASSWORD: $INTERAC_SERVICE_PASSWORD
      MONGODB_PASSWORD: $MONGODB_PASSWORD
    image: interac-auth-service
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  auth-mongodb:
    build: mongodb
    ports:
      - 25000:27017
    environment:
      MONGODB_PASSWORD: $MONGODB_PASSWORD
    image: interac-mongodb
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  interac-service:
    build: interac-service
    ports:
      - 6000:6000
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      INTERAC_SERVICE_PASSWORD: $INTERAC_SERVICE_PASSWORD
      MONGODB_PASSWORD: $MONGODB_PASSWORD
    image: interac-service
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  interac-mongodb:
    build: mongodb
    ports:
      - 26000:27017
    environment:      
      MONGODB_PASSWORD: $MONGODB_PASSWORD
    image: interac-mongodb
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"
  
  monitoring:
    build: monitoring
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    image: interac-monitoring
    restart: always
    ports:
      - 9000:8080
      - 8989:8989
    logging:
      options:
        max-size: "10m"
        max-file: "10"
