security:
  oauth2:
    client:
      clientId: interac-service
      clientSecret: ${INTERAC_SERVICE_PASSWORD}
      accessTokenUri: http://auth-service:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  data:
    mongodb:
      host: interac-mongodb
      username: user
      password: ${MONGODB_PASSWORD}
      database: interac
      port: 27017

server:
  context-path: /interac
  port: 6000
